# Generated by Django 5.0.6 on 2024-07-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_mantencion', models.CharField(choices=[('domicilio', 'A domicilio'), ('local', 'En el local')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
