# Generated by Django 5.0.6 on 2024-07-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantencion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='mantencion',
            name='tipo_mantencion',
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='direccion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
